### ISSUE TITLE
Mod 0 Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [vjt960/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [x]  Files and directories are structured correctly.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [x]  Directories and files were named and structured correctly.
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
* [x]  The attributes chosen for **Class #2** represent states or characteristics.
* [x]  The attributes chosen for **Class #3** represent states or characteristics.
* [x]  The methods chosen for **Class #1** represent behaviors or actions.
* [x]  The methods chosen for **Class #2** represent behaviors or actions.
* [x]  The methods chosen for **Class #3** represent behaviors or actions.
* [ ]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [ ]  Individual changes were added and committed separately with a properly formatted commit message.
* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [x]   Technical Ready
* [ ]   Pending
* [ ]   Not Ready

**Comment by timomitchel** [comment]
Great job on the assessment Vinton! Love seeing that you uses `markdown` for the Top Down Design section. A few things to note about attributes. You have `rating` listed as a float in one class and an integer in another. I would keep them both as floats. That being said, this  `rating` would be a calculation of the average of all `ratings` which could be stored as an array of ints. Because `rating` is returning a calculation, it would be a method or a function of our class. Be sure to be careful about spaces when naming something. See: `currently open`. And, if we are listing something as an array that implies that there will be multiple elements in the array, so we should name this attribute plurally. Overall great job and good luck with module 1.
